export const PACKAGE_NAME = '@kanbots/api';

export {
  createSupervisor,
  type AgentSupervisor,
  type CreateSupervisorOptions,
  type ResumeRunInput,
  type StartRunInput,
} from './agent-runs/supervisor.js';
export {
  reconcileIssueLabels,
  type ReconcileLabelsResult,
} from './workspace-reconcile.js';
export {
  bootstrapWorkspace,
  type WorkspaceBootstrapResult,
} from './workspace-bootstrap.js';

export {
  createHandlers,
  type CreateHandlersOptions,
  type HandlerDeps,
  type Handlers,
  type SubscriptionRegistry,
} from './handlers/index.js';
export type {
  AgentCheck,
  AgentEvent,
  AgentEventType,
  AgentKey,
  AgentRun,
  AgentRunEventPayload,
  AgentRunStatus,
  BridgeChannels,
  Card,
  CardStatus,
  CardType,
  ChannelArgs,
  ChannelName,
  ChannelResult,
  CheckKind,
  Comment,
  Config,
  CreateIssueInput,
  DecisionPayload,
  DecoratedIssue,
  DiffFile,
  DiffFileStatus,
  DiffPayload,
  DispatchResult,
  DraftedIssue,
  DraftIssueFn,
  DraftIssueInput,
  SuggestFeatureBacklogEntry,
  SuggestFeatureFn,
  SuggestFeatureInput,
  EventSubscribeResult,
  ForkRunResult,
  Issue,
  IssueActiveRunPayload,
  IssueDetail,
  Message,
  PendingDecisionPayload,
  PostMessageResult,
  PreviewState,
  PreviewStatePayload,
  ResolveCardResult,
  Role,
  RunStatsResult,
  SplitResult,
  StatusKey,
  ThreadPayload,
  UpdateIssuePatch,
  UploadAttachmentResult,
  Workspace,
  WorkspaceFolderPayload,
} from './bridge.js';
